version: "3.9"
services:
  openresty:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    container_name: openresty-server
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - shared-data:/usr/local/openresty/nginx/logs
    restart: unless-stopped
    command: ["openresty", "-g", "daemon off;"]

  elixir_app:
    build: .
    ports:
      - "4000:4000"
    networks:
      - app_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app_network
    depends_on:
      - elixir_app

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  shared-data:
    driver: local