global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["elixir_app:4000"]
  - job_name: "telemetry_metrics_prometheus"
    static_configs:
      - targets: ["elixir_app:9568"]