FROM openresty/openresty:alpine

COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf

COPY default.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /var/log/nginx && chmod 777 /var/log/nginx

EXPOSE 8080

CMD ["openresty", "-g", "daemon off;"]
